### ISSUE TITLE
Container missing from ListContainers call

### ISSUE THREAD

**Issue by zanemcca** [tutumcloud/go-tutum#12]
I have noticed a few times when I start up a new stack with a lot of services I will be missing a container when I call `ListContainers`.
I tried the tutum CLI command `tutum container ps` and it successfully listed the missing containers. I also noticed that the linked from containers have the appropriate environment variables.

**Comment by zanemcca** [comment]
I found out that if I stop the container that is missing, destroy its node cluster, then create a new cluster and restart the container it will work properly. 
After I did this though I had to do a redeploy of the container and it disappeared again.

**Comment by MaximeHeckel** [comment]
Hi @zanemcca I will take a look at this and try to reproduce.
How many containers do you wanted to list exactly ?

**Comment by MaximeHeckel** [comment]
I will soon push the fix

**Comment by zanemcca** [comment]
Hi @MaximeHeckel thanks a lot.
I had between 16 and 25 containers running when I ran into the issue.

**Comment by MaximeHeckel** [comment]
It has been solved in the latest merge, you can give it a try. I'm closing the issue, reopen it if needed.
