### ISSUE TITLE
Container type missing Linked_to_container

### ISSUE THREAD

**Issue by pilwon** [tutumcloud/go-tutum#23]
[Container.Linked_to_container](https://docs.tutum.co/v2/api/?go#container) is missing in the library.

We need to make these changes:
### Add:
- [ ] Working_dir
- [ ] Last_metric
- [ ] Linked_to_container
- [ ] Link_variables
### Remove:
- [ ] Application
- [ ] Autoreplace
- [ ] Container_size
- [ ] Current_num_containers
- [ ] Unique_name
### Add:
- [ ] Synchronized
- [ ] Running_num_containers
- [ ] Stopped_num_containers
- [ ] Working_dir
- [ ] Sequential_deployment
- [ ] Cpu_shares
- [ ] Memory
- [ ] Linked_from_service
- [ ] Bindings
- [ ] Roles
- [ ] Link_variables
- [ ] Privileged
- [ ] Deployment_strategy
- [ ] Tags
### Remove:
- [ ] Container_size
- [ ] Exit_code
- [ ] Exit_code_message
- [ ] Unique_name
### Rename:
- [ ] Service --> Services

**Comment by pilwon** [comment]
Submitted PR #24 that fixes everything summarized above + extra

**Comment by MaximeHeckel** [comment]
So we can close this.
