### ISSUE TITLE
The container Exec function cannot end correctly and there is a mistake in the api doc

### ISSUE THREAD

**Issue by Wennn** [tutumcloud/go-tutum#35]
When I use the Exec function to execute a command inside a container, it cannot end correctly and print endless something like "2015/11/05 09:07:03 websocket: close 1000 ".
And the example in the doc says "c := make(chan string)", but it cannot work. After I read the code, I think it should be "c := make(chan tutum.Exec)". I try it and it works. I think it should be discussed.

**Comment by MaximeHeckel** [comment]
Hey!
Thank you for the feedback we're going to check this right now and fix the mistake in the doc

**Comment by MaximeHeckel** [comment]
Ok so I think your issue is related with #33 it will soon be merged. I'll make sure to update the doc ASAP
