### ISSUE TITLE
Container structure does not match documentation

### ISSUE THREAD

**Issue by zanemcca** [tutumcloud/go-tutum#8]
According to the documentation found [here](https://docs.tutum.co/v2/api/?go#container) the container struct should have private_ip and container_envvars but it does not.

**Comment by MaximeHeckel** [comment]
Thank you for noticing that, I'm going to add that ASAP

**Comment by zanemcca** [comment]
NP Thanks for the quick reply. 
I started to add it but I will leave it for you because there are some more structs missing that I am not sure how you want to implement. Here is the list
- Bindings
- Cpu_shares
- Last_metric
- Linked_to_containers
- Link_variables
- Memory
- Node
- Privileged
- Roles
- Service
- Synchronized

Also "Exit_code_message" is spelt "Exit_code_msg" in the documentation. Not sure which way it is supposed to be spelt.

**Comment by MaximeHeckel** [comment]
Thank you ! I'll add those as well. I'll you updated

**Comment by MaximeHeckel** [comment]
Added in 4f8d727bbd092f67ffb7b16ee0a8e291d6bee597

Thank you for your help !

**Comment by zanemcca** [comment]
Thanks a lot @MaximeHeckel
